--[[
	BagSync Localization
--]]

if ( GetLocale() == "zhCN" ) then

	BAGSYNC_NUM_BAGS = '背包: %d'
	BAGSYNC_NUM_BANK = '银行: %d'
	BAGSYNC_EQUIPPED = '已装备: %d'
	BAGSYNC_NUM_GUILDBANK = 'Guild: %d'
	BAGSYNC_NUM_MAILBOX = 'Mailbox: %d'
	BAGSYNC_SEARCH = 'Search'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = 'Tokens'
	BAGSYNC_PROFILES = 'Profiles'
	BAGSYNC_PROFILES_TT = 'Select a profile to delete.\nNOTE: This is irreversible!'
	BAGSYNC_PROFILES_DELETE = 'Delete'
	BAGSYNC_PROFILES_CONFIRM = 'Confirm'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Does a quick search for an item'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Opens the search window'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Displays a tooltip with the amount of gold on each character.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Opens the tokens/currency window.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Opens the profiles window.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
elseif ( GetLocale() == "ruRU" )  then
	--thanks to senryo from WOWInterface
	
	BAGSYNC_NUM_BAGS = 'В сумке: %d'
	BAGSYNC_NUM_BANK = 'В банке: %d'
	BAGSYNC_EQUIPPED = 'На персонаже: %d'
	BAGSYNC_NUM_GUILDBANK = 'В гильдбанке: %d'
	BAGSYNC_NUM_MAILBOX = 'Mailbox: %d'
	BAGSYNC_SEARCH = 'Search'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = 'Tokens'
	BAGSYNC_PROFILES = 'Profiles'
	BAGSYNC_PROFILES_TT = 'Select a profile to delete.\nNOTE: This is irreversible!'
	BAGSYNC_PROFILES_DELETE = 'Delete'
	BAGSYNC_PROFILES_CONFIRM = 'Confirm'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Does a quick search for an item'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Opens the search window'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Displays a tooltip with the amount of gold on each character.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Opens the tokens/currency window.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Opens the profiles window.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
elseif ( GetLocale() == "zhTW" ) then

	BAGSYNC_NUM_BAGS = '背包: %d'
	BAGSYNC_NUM_BANK = '銀行: %d'
	BAGSYNC_EQUIPPED = '已裝備: %d'
	BAGSYNC_NUM_GUILDBANK = 'Guild: %d'
	BAGSYNC_NUM_MAILBOX = 'Mailbox: %d'
	BAGSYNC_SEARCH = 'Search'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = 'Tokens'
	BAGSYNC_PROFILES = 'Profiles'
	BAGSYNC_PROFILES_TT = 'Select a profile to delete.\nNOTE: This is irreversible!'
	BAGSYNC_PROFILES_DELETE = 'Delete'
	BAGSYNC_PROFILES_CONFIRM = 'Confirm'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Does a quick search for an item'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Opens the search window'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Displays a tooltip with the amount of gold on each character.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Opens the tokens/currency window.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Opens the profiles window.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
elseif ( GetLocale() == "frFR" ) then
	--thanks to cacahuete from WOWInterface
	
	BAGSYNC_NUM_BAGS = 'Sacs: %d'
	BAGSYNC_NUM_BANK = 'Banque: %d'
	BAGSYNC_EQUIPPED = 'Équipé: %d'
	BAGSYNC_NUM_GUILDBANK = 'Guilde: %d'
	BAGSYNC_NUM_MAILBOX = 'Mailbox: %d'
	BAGSYNC_SEARCH = 'Search'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = 'Tokens'
	BAGSYNC_PROFILES = 'Profiles'
	BAGSYNC_PROFILES_TT = 'Select a profile to delete.\nNOTE: This is irreversible!'
	BAGSYNC_PROFILES_DELETE = 'Delete'
	BAGSYNC_PROFILES_CONFIRM = 'Confirm'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Does a quick search for an item'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Opens the search window'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Displays a tooltip with the amount of gold on each character.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Opens the tokens/currency window.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Opens the profiles window.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
elseif ( GetLocale() == "koKR" ) then
	--thanks to zinzzalimp from WOWInterface
	
	BAGSYNC_NUM_BAGS = '가방: %d'
	BAGSYNC_NUM_BANK = '은행: %d'
	BAGSYNC_EQUIPPED = '착용중: %d'
	BAGSYNC_NUM_GUILDBANK = '길드은행: %d'
	BAGSYNC_NUM_MAILBOX = '우편함: %d'
	BAGSYNC_SEARCH = '검색'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = '문장'
	BAGSYNC_PROFILES = '프로필'
	BAGSYNC_PROFILES_TT = '삭제할 프로필을 선택하세요.\nNOTE: 되돌릴수 없습니다!!!'
	BAGSYNC_PROFILES_DELETE = '삭제'
	BAGSYNC_PROFILES_CONFIRM = '확인'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - 빠른 아이템 찾기'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - 검색창 열기'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - 툴팁에 각 케릭터의 골드량을 표시합니다.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - 문장/화폐창을 엽니다'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - 프로필 창을 엽니다.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
elseif ( GetLocale() == "deDE" ) then
	--thanks to Schnubby from WOWInterface

	BAGSYNC_NUM_BAGS = 'Taschen: %d'
	BAGSYNC_NUM_BANK = 'Bank: %d'
	BAGSYNC_EQUIPPED = 'Angelegt: %d'
	BAGSYNC_NUM_GUILDBANK = 'Gilde: %d'
	BAGSYNC_NUM_MAILBOX = 'Post: %d'
	BAGSYNC_SEARCH = 'Suche'
	BAGSYNC_SEARCH_TOTAL = 'Gesamt:'
	BAGSYNC_TOKENS = 'Abzeichen'
	BAGSYNC_PROFILES = 'Profile'
	BAGSYNC_PROFILES_TT = 'Wähle ein Profil zum löschen aus.\nINFO: Dies ist nicht umkehrbar!'
	BAGSYNC_PROFILES_DELETE = 'Löschen'
	BAGSYNC_PROFILES_CONFIRM = 'Bestätigen'
	BAGSYNC_BINDING_SEARCH = 'Öffne/Schließe Suche'
	BAGSYNC_BINDING_TOKEN = 'Öffne/Schließe Abzeichen'
	BAGSYNC_BINDING_PROFILES = 'Öffne/Schließe Profile'
	BAGSYNC_DATABASE_FIX_ALERT = 'Die Funktion FixDB wurde ausgeführt! Die Datenbank wurde optimiert!'
	BAGSYNC_SWITCH_ON = 'An'
	BAGSYNC_SWITCH_OFF = 'Aus'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Nach einem Item suchen'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Öffnet das Suchfenster'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Zeigt einen Tooltip mit dem Gold eines jeden Charakters.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Öffnet das Abzeichenfenster.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Öffnet das Profilfenster.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Führt eine Reparatur der Datenbank (FixDB) aus.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Zeigt/Verbirgt die [Gesamt] Anzeige in Tooltips für Items und in der Goldanzeige.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
else

	BAGSYNC_NUM_BAGS = 'Bags: %d'
	BAGSYNC_NUM_BANK = 'Bank: %d'
	BAGSYNC_EQUIPPED = 'Equipped: %d'
	BAGSYNC_NUM_GUILDBANK = 'Guild: %d'
	BAGSYNC_NUM_MAILBOX = 'Mailbox: %d'
	BAGSYNC_SEARCH = 'Search'
	BAGSYNC_SEARCH_TOTAL = 'Total:'
	BAGSYNC_TOKENS = 'Tokens'
	BAGSYNC_PROFILES = 'Profiles'
	BAGSYNC_PROFILES_TT = 'Select a profile to delete.\nNOTE: This is irreversible!'
	BAGSYNC_PROFILES_DELETE = 'Delete'
	BAGSYNC_PROFILES_CONFIRM = 'Confirm'
	BAGSYNC_BINDING_SEARCH = 'Toggle Search'
	BAGSYNC_BINDING_TOKEN = 'Toggle Tokens'
	BAGSYNC_BINDING_PROFILES = 'Toggle Profiles'
	BAGSYNC_DATABASE_FIX_ALERT = 'A FixDB has been performed on BagSync!  The database is now optimized!'
	BAGSYNC_SWITCH_ON = 'ON'
	BAGSYNC_SWITCH_OFF = 'OFF'
	BAGSYNC_SLASH_CMD1 = '[itemname]'
	BAGSYNC_SLASH_CMD2 = 'search'
	BAGSYNC_SLASH_CMD3 = 'gold'
	BAGSYNC_SLASH_CMD4 = 'tokens'
	BAGSYNC_SLASH_CMD5 = 'profiles'
	BAGSYNC_SLASH_CMD6 = 'fixdb'
	BAGSYNC_SLASH_CMD7 = 'total'
	BAGSYNC_SLASH_CMD8 = 'guildname'
	BAGSYNC_SLASH_CMD9 = 'throttle'
	BAGSYNC_SLASH1 = '/bgs '..BAGSYNC_SLASH_CMD1..' - Does a quick search for an item'
	BAGSYNC_SLASH2 = '/bgs '..BAGSYNC_SLASH_CMD2..' - Opens the search window'
	BAGSYNC_SLASH3 = '/bgs '..BAGSYNC_SLASH_CMD3..' - Displays a tooltip with the amount of gold on each character.'
	BAGSYNC_SLASH4 = '/bgs '..BAGSYNC_SLASH_CMD4..' - Opens the tokens/currency window.'
	BAGSYNC_SLASH5 = '/bgs '..BAGSYNC_SLASH_CMD5..' - Opens the profiles window.'
	BAGSYNC_SLASH6 = '/bgs '..BAGSYNC_SLASH_CMD6..' - Runs the database fix (FixDB) on BagSync.'
	BAGSYNC_SLASH7 = '/bgs '..BAGSYNC_SLASH_CMD7..' - Toggles the [Total] display in tooltips and gold display.'
	BAGSYNC_SLASH8 = '/bgs '..BAGSYNC_SLASH_CMD8..' - Toggles the [Guild Name] display in tooltips.'
	BAGSYNC_SLASH9 = '/bgs '..BAGSYNC_SLASH_CMD9..' - Toggles the throttle when displaying tooltips. (ON = Prevents Lag).'
	
end

